# Basic Information 
title: Pengsong Zhang
position: Ph.D. Student
affiliation: University of Toronto
affiliation_link: https://www.utoronto.ca/
affiliation_logo: ./assets/img/uoft_logo.svg
email: pengsong.zhang (at) mail.utoronto.ca


# Search Engine Optimization (SEO)
keywords: pengsong zhang, zhang pengsong, pengsongzhang, zhangpengsong
canonical: https://universea.github.io/
description: Pengsong Zhang is a Ph.D. student at University of Toronto. His research lies in micro-/nano robotics, reinforcement learning, computer vision and LLM agents.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=fljNSIsAAAAJ&hl=en
cv_link: assets/files/CV-Pengsong_Zhang.pdf
github_link: https://github.com/universea/
linkedin: https://www.linkedin.com/in/pengsongzhang/
twitter: https://twitter.com/pengsongzhang96

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/Utoronto_coa.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: This pages was build with minimal-light.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
